# Generated by Django 5.2.5 on 2025-09-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hashpassword',
        ),
    ]
