# Generated by Django 5.2.5 on 2025-11-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animefollow',
            name='notify_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
