# Generated by Django 5.2.5 on 2025-11-26 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_animefollow_notify_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListJoinRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='src.list')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List Join Request',
                'verbose_name_plural': 'List Join Requests',
                'db_table': 'list_join_requests',
                'ordering': ['-requested_at'],
                'unique_together': {('list', 'user', 'status')},
            },
        ),
    ]
