# Generated by Django 5.2.5 on 2025-11-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_listjoinrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listjoinrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'List Request', 'verbose_name_plural': 'List Requests'},
        ),
        migrations.AlterUniqueTogether(
            name='listjoinrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listjoinrequest',
            name='request_type',
            field=models.CharField(choices=[('join', 'Join List'), ('edit_permission', 'Request Edit Permission')], default='join', help_text='Type of request: join (become member) or edit_permission (upgrade to editor)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='listjoinrequest',
            unique_together={('list', 'user', 'status', 'request_type')},
        ),
    ]
