# Generated by Django 5.2.5 on 2025-12-02 09:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_listjoinrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user liked this list')),
                ('list', models.ForeignKey(help_text='The list being liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='src.list')),
                ('user', models.ForeignKey(help_text='User who likes the list', on_delete=django.db.models.deletion.CASCADE, related_name='liked_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List Like',
                'verbose_name_plural': 'List Likes',
                'db_table': 'list_likes',
                'ordering': ['-liked_at'],
                'indexes': [models.Index(fields=['user', '-liked_at'], name='list_likes_user_id_c61cf5_idx'), models.Index(fields=['list', '-liked_at'], name='list_likes_list_id_3abe2b_idx')],
                'unique_together': {('user', 'list')},
            },
        ),
    ]
