# Generated by Django 5.2.8 on 2025-12-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_listlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture (max 1MB)', null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
