# Generated by Django 5.2.5 on 2025-12-04 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeNotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='anime_notification_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notify_before_hours', models.IntegerField(default=24, help_text='Notify user X hours before episode airs')),
                ('enabled', models.BooleanField(default=True)),
                ('notify_by_email', models.BooleanField(default=True)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anime Notification Preference',
                'verbose_name_plural': 'Anime Notification Preferences',
                'db_table': 'anime_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='AnimeAiringNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('anilist_id', models.IntegerField(help_text='AniList anime ID')),
                ('episode_number', models.IntegerField()),
                ('airing_at', models.DateTimeField(help_text='When the episode will air')),
                ('notify_at', models.DateTimeField(help_text='When to send notification')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_anime_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anime Airing Notification',
                'verbose_name_plural': 'Anime Airing Notifications',
                'db_table': 'anime_airing_notifications',
                'ordering': ['-notify_at'],
                'indexes': [models.Index(fields=['notify_at', 'status'], name='idx_notify_status'), models.Index(fields=['user', 'anilist_id'], name='idx_user_anime'), models.Index(fields=['status', 'created_at'], name='idx_status_created')],
                'unique_together': {('user', 'anilist_id', 'episode_number')},
            },
        ),
    ]
